### PR TITLE
Upd: Screenshot method DroidCast_raw update

### PR DESCRIPTION
**Pull request by YuuLong**
* Upd: Screenshot method DroidCast_raw update

* Opt: Refactor module/device/method/droidcast.py for improved functionality

The module/device/method/droidcast.py has been refactored to improve its functionality and remove unnecessary code. Here are the key changes:

- Removed the unnecessary droidcast_raw_port attribute.
- Updated the droidcast_url method to use '/preview' as the default URL for DroidCast.
- Rename droidcast_init and droidcast_raw_init to droidcast_start and droidcast_raw_start.
- Add droidcast_init to reuse the common parts of droidcast_start and droidcast_raw_start.
- Removed the droidcast_raw_wait_startup method as it is no longer needed.
- Updated the droidcast_uninstall method to remove the deletion of DroidCast APK.

These changes aim to simplify the DroidCast class and improve its overall functionality.

* Fix: Droidcast cannot start due to port occupation
* Fix: Fixed an issue that could not be used on Android10 and Android11.

### CODE REVIEW

**Comment by runhey** [comment]
```
if self.config.DROIDCAST_VERSION == 'DroidCast':
            logger.attr('DroidCast', self.droidcast_url())
            self.droidcast_wait_startup()
        elif self.config.DROIDCAST_VERSION == 'DroidCast_raw':
            logger.attr('DroidCast_raw', self.droidcast_raw_url())
            self.droidcast_wait_startup()
        else:
            logger.error(f'Unknown DROIDCAST_VERSION: {self.config.DROIDCAST_VERSION}')
```

**Comment by YuuLong** [comment]
> ```
> if self.config.DROIDCAST_VERSION == 'DroidCast':
>             logger.attr('DroidCast', self.droidcast_url())
>             self.droidcast_wait_startup()
>         elif self.config.DROIDCAST_VERSION == 'DroidCast_raw':
>             logger.attr('DroidCast_raw', self.droidcast_raw_url())
>             self.droidcast_wait_startup()
>         else:
>             logger.error(f'Unknown DROIDCAST_VERSION: {self.config.DROIDCAST_VERSION}')
> ```

好的，我看看

**Comment by runhey** [comment]
你不是在这个的基础上改的https://github.com/runhey/OnmyojiAutoScript/pull/246

**Comment by YuuLong** [comment]
> 你不是在这个的基础上改的#246

不是，我最开始忘记同步更新了，然后后面合并更新再提交的，合并的时候出了点问题，我也注意到，这里我后续会改回去的，问题是现在的droidcast方法我不知道还有没有问题

**Comment by runhey** [comment]
我跟着加了使用screenshot_droidcast可以，使用screenshot_droidcast_raw报错Requesting screenshots from `DroidCast_raw` but server is `DroidCast

**Comment by runhey** [comment]
image
screenshot_droidcast_raw可以了

**Comment by YuuLong** [comment]
> image screenshot_droidcast_raw可以了



> image screenshot_droidcast_raw可以了

嗷嗷我明白了，那我回滚一下更新，先同步再改。删个库等会再pr

**Comment by runhey** [comment]
别动就这样

**Comment by runhey** [comment]
我更好了，有空测一下速度

**Comment by YuuLong** [comment]
> 我更好了，有空测一下速度

好滴好滴！

**Pull request merged**
