### PR TITLE
fix: Change the roi of ticket of GoryouRealm.

### PR DESCRIPTION
**Pull request by YuuLong**
## 测试图片使用的是 #111 中的图片，该pr旨在修复 #111 和 #110 中的同类问题

### CODE REVIEW

**Comment by YuuLong** [comment]
经测试，四位数情况依然可以正常识别

**Comment by runhey** [comment]
image
五位，还有那个突破不太行

**Comment by runhey** [comment]
没看明白，最近压力比较大先放着吧。

**Comment by YuuLong** [comment]
> 没看明白，最近压力比较大先放着吧。

猜到原因了，大概是出来的时候聊天框比较短，也就是聊天框遮挡了，但是在票的位置没文字，没识别到东西。然后我预留了检测票的时候二次识别奖励，但是忘记加这里的后处理了，这个可以改一下。

**Comment by YuuLong** [comment]
从目前的情况来看，是可以正常处理聊天框，并且直到出现票数的，就是忘记加一小段代码了，疏忽了这里

**Comment by YuuLong** [comment]
> image 五位，还有那个突破不太行

五位数出现了多识别一位的情况，我把roi再改小点，这里还真是玄学

不过800那里用老的roi，真是稳定触发识别成00，就很神奇

**Comment by YuuLong** [comment]
> 图省事贴这里
> 
> ```
> ───────────────────────────── GENERAL BATTLE START ─────────────────────────────
> 2023-10-11 15:31:02.589 |     INFO | GENERAL BATTLE START                                                               
> 2023-10-11 15:31:02.595 |     INFO | Current count: 5                                                                   
> 2023-10-11 15:31:02.885 |     INFO | Start battle process                                                               
> 2023-10-11 15:31:20.505 |     INFO | Battle result is win                                                               
> 2023-10-11 15:31:20.516 |     INFO | Reconfirm the results of the battle                                                
> 2023-10-11 15:31:20.810 |     INFO | Click (  92,  578) @ GB_WIN                                                        
> 2023-10-11 15:31:22.004 |     INFO | Get reward                                                                         
> 2023-10-11 15:31:22.305 |     INFO | Click ( 718,  624) @ GB_REWARD                                                     
> 2023-10-11 15:31:23.819 |     INFO | Click (1209,  223) @ GB_REWARD                                                     
> 2023-10-11 15:31:25.680 |     INFO | [TEXT 0.010s] []                                                                   
> 2023-10-11 15:31:25.686 |     INFO | [TEXT] Try to detect vertically                                                    
> 2023-10-11 15:31:26.202 |     INFO | [TEXT 0.512s] []                                                                   
> 2023-10-11 15:31:26.210 |     INFO | [TEXT]: No text detected in ROI                                                    
> 2023-10-11 15:31:26.839 |     INFO | [NUMBER 0.007s] [11/30]                                                            
> 2023-10-11 15:31:26.887 |     INFO | Find one medal [RES_MEDAL_5], order is 4                                           
> 2023-10-11 15:31:27.535 |     INFO | Click ( 347,  300) @ partition_4                                                   
> 2023-10-11 15:31:28.122 |     INFO | Click ( 380,  531) @ RES_FIRE                                                      
> 2023-10-11 15:31:29.323 |     INFO | Click fire 4 success                                                               
> ───────────────────────────── GENERAL BATTLE START ─────────────────────────────
> 2023-10-11 15:31:29.330 |     INFO | GENERAL BATTLE START                                                               
> 2023-10-11 15:31:29.334 |     INFO | Current count: 6                                                                   
> 2023-10-11 15:31:29.556 |     INFO | Start battle process                                                               
> 2023-10-11 15:31:49.973 |     INFO | Battle result is win                                                               
> 2023-10-11 15:31:49.987 |     INFO | Reconfirm the results of the battle                                                
> 2023-10-11 15:31:50.278 |     INFO | Click ( 848,   64) @ GB_WIN                                                        
> 2023-10-11 15:31:51.770 |     INFO | Get reward                                                                         
> 2023-10-11 15:31:52.073 |     INFO | Click (1231,  216) @ GB_REWARD                                                     
> 2023-10-11 15:31:53.885 |     INFO | [TEXT 0.005s] []                                                                   
> 2023-10-11 15:31:53.889 |     INFO | [TEXT] Try to detect vertically                                                    
> 2023-10-11 15:31:54.360 |     INFO | [TEXT 0.466s] []                                                                   
> 2023-10-11 15:31:54.367 |     INFO | [TEXT]: No text detected in ROI                                                    
> 2023-10-11 15:31:55.002 |     INFO | [NUMBER 0.010s] []                                                                 
> 2023-10-11 15:31:55.008 |     INFO | [NUMBER] Try to detect vertically                                                  
> 2023-10-11 15:31:55.444 |     INFO | [NUMBER 0.431s] ['哪里：弄']                                                       
> 2023-10-11 15:31:55.449 |  WARNING | Unexpected ocr result: None                                                        
> 2023-10-11 15:31:55.486 |     INFO | [TEXT 0.018s] []                                                                   
> 2023-10-11 15:31:55.490 |     INFO | [TEXT] Try to detect vertically                                                    
> 2023-10-11 15:31:55.981 |     INFO | [TEXT 0.485s] ['哪里：弄']                                                         
> 2023-10-11 15:31:56.027 |     INFO | [TEXT 0.011s] [10/30]                                                              
> 2023-10-11 15:31:56.037 |  WARNING | Execute raid failed, no ticket                                                     
> 2023-10-11 15:31:56.313 |     INFO | Click (1191,  127) @ RES_BACK_RED                                                  
> 2023-10-11 15:31:57.507 |     INFO | Click (1229,  112) @ RES_BACK_RED                                                  
> 2023-10-11 15:31:58.108 |     INFO | UI get current page                                                                
> 2023-10-11 15:31:58.127 |     INFO | [UI] page_exploration                                                              
> 2023-10-11 15:31:58.133 |     INFO | <<< UI GOTO PAGE_MAIN >>>                                                          
> 2023-10-11 15:31:58.143 |     INFO | Page switch: page_exploration -> page_main                                         
> 2023-10-11 15:31:58.152 |     INFO | Click (  37,   40) @ PAGE_BACK_BLUE                                                
> 2023-10-11 15:32:00.267 |     INFO | Page arrive: page_main                                                             
> 2023-10-11 15:32:00.270 |     INFO | Delay task `realm_raid` to 2023-10-12 15:32:00 (success=True, server_update=True)  
> 2023-10-11 15:32:00.276 |     INFO | [realm_raid.scheduler.next_run] 2023-10-12 15:32:00                                
> 2023-10-11 15:32:00.296 |     INFO | Scheduler: End task `RealmRaid`                                                    
> 2023-10-11 15:32:00.315 |     INFO | Pending tasks: ['DailyTrifles', 'WantedQuests', 'BondlingFairyland', 'RichMan',    
> 'Pets', 'TalismanPass', 'SoulsTidy', 'Delegation', 'WeeklyTrifles', 'MysteryShop']                                      
> 2023-10-11 15:32:00.323 |     INFO | [Task] DailyTrifles (Enable, 5, 2023-10-11 08:00:00)                               
> 2023-10-11 15:32:00.328 |     INFO | Update tasks oas1                                                                  
> 2023-10-11 15:32:00.334 |     INFO | Scheduler: Start task `DailyTrifles`       
> ```
已修复，写代码的疏漏，只想着出现异常处理，忘记把处理后的票数重新识别了

**Comment by Small-Chai** [comment]
整千的票数还是会识别报错，直接返回庭院

**Pull request merged**
